# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: BuildChat
        working-directory: ./chat
        run: |
          go mod tidy
          go build -v ./...

      - name: BuildClient
        working-directory: ./client
        run: |
          go mod tidy
          go build -v ./...

      - name: BuildStorageService
        working-directory: ./storage
        run: |
          go mod tidy
          go build -v ./...


      - name: LintClient
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./client

      - name: LintChat
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./chat

      - name: LintStorageService
        uses: golangci/golangci-lint-action@v3
        with:
            version: latest
            working-directory: ./client

      - name: Test
        working-directory: ./chat
        run: |
          go mod tidy
          go test -v -race -coverpkg=./... ./...
